### PR TITLE
Improve snippets and add slash command

### PR DESCRIPTION
**Pull request by hughess**
Adds a slash command to open Evidence snippets, and simplifies the appearance of the snippets

CleanShot 2023-06-22 at 14 33 29

### CODE REVIEW

**Comment by mcrascal** [comment]
I like this a lot -- I got a warning while building it from the branch, but I was still able to play with it. 

1. I have some concern about including components that only work inside the context of a slot. E.g. `<Column/>`, but I think the right way to build around that is to add informative error states for all of those when they are referenced outside of the expected parent component. As an example, `<Column />` breaks if you include it outside of a data table. 
2. Generic defaults like `query_name` feel like a better choice to me than ones that work with the needful things db in the template project. I think you learn something the first time you change query_name to reference an actual query on the page, and I think over time I'd find it kind of weird to have `orders` or similar defaulted into my snippets.

**Comment by hughess** [comment]
Good point - I think there's a few ways we can handle those nested components:
1. Include an error state for the component when used outside the parent component (I think they all have this actually)
2. Include a warning message in the snippet to say it can only be used within the parent component
3. Only include in snippets as a child of the parent component (there's a `DataTableWithColumns` example in there now) - not sure the best way to name ones like that
   - For ReferenceLine and ReferenceArea that wouldn't really be possible, but it might be worth including one example just to show how it works (e.g., `LineChartWithAnnotations`)

Yea I agree on the working examples - I played around with it and it's really cool to have it work on save, but it relies on having the specific query on that page, which I didn't find that intuitive

**Comment by hughess** [comment]
I was thinking of a way to get the info to users quickly about the slash commands and found that we can add in "decorations" to the text.

This was tricky to set up and there's a little bit of testing to make sure it doesn't break in some situations, but I've got it set up to show next to the cursor when the current line is empty:

CleanShot 2023-06-22 at 18 32 06

**Comment by hughess** [comment]
Update: I've included that prompt message in the branch. It seems to work pretty well.

Ended up using the same text colour as gitlens' blame comments since it works well for all VS Code color themes.

@mcrascal @archiewood let me know if you think that message is too intrusive

**Comment by archiewood** [comment]
I like feature in general. Some thoughts:

## Using slash
 Slash is a character used in various places in Evidence markdown (svelte + sql). In particular:

 ### Writing components or html elements directly 
image

### Writing paths in images and links
image

### Division operator in SQL
image

### Suggested Solutions
My two suggestions here would be either:
1. have the suggestions start on `<` rather than `/`
2. try to turn off suggestions when they are not on a empty newline

## Prompt
I think the prompt is quite eager. Is it possible to:
- delay it by a couple of seconds after you hit enter before it shows up
- prevent it competing with Github Copilot: 
image
- (if we switched from `/` to `<` it would remove the need for the prompt, as the first character when starting a component is the same as the prompt)

**Comment by hughess** [comment]
### Slash Command
Ok I looked into changing the character and unfortunately `<` is a reserved character in VSCode so we can't use it as a keybinding.

I've added a fix to the slash so it only shows up on empty lines (including lines that are only whitespace).

### Prompt
This also includes better positioning of the prompt so it's less likely to cause issues interfering with actual text on your page.

I'm a bit concerned about the codespaces interference - will need to take a look at that.

I was also hoping I could access which language the cursor is currently in so I could disable the prompt within SQL blocks, but no luck on that so far.

CleanShot 2023-06-23 at 08 33 19

**Comment by hughess** [comment]
I've also thrown in some more snippets - we don't need to keep all of these, but I was thinking through which things are:
- Annoying to write
- Hard to remember syntax
- Not currently discoverable

CleanShot 2023-06-23 at 08 38 20

**Comment by archiewood** [comment]
It looks from the drop-down suggestions like you might be able to add icons?

Maybe add icons to distinguish components from markdown and other features.

More generally I really like the page param one. Another on this theme would be the js filter syntax `.filter(d=>...)`

I'm less wild about shortcuts for vanilla markdown things like today and numbered lists etc. 

I think for lists it would be nice to auto detect you have started a list and then add another list character on enter but that's a separate feature I think.

**Comment by hughess** [comment]
Good idea on the icons - I'll look into that.

There is a filter snippet, but it's part of the javascript snippets, so it only appears if you start typing `filter` and wait a couple of seconds. I think including in the main list is probably better - it'll be a good reminder on the syntax.

I agree about shortcuts for vanilla markdown, but I was thinking the benefit for those ones is more about discoverability for a new user (i.e. this is everything you can do in Evidence) rather than an automation. I can remove them if we think they add too much clutter. Icons would help with that for sure.

Great idea for lists

**Comment by hughess** [comment]
After some investigation, it looks like customizing the icons for snippets is not possible - apparently that's VS Code's snippet icon. Or at least it's not possible without developing a custom menu.

I've added a snippet for filtered query result.

**Comment by hughess** [comment]
I looked into the copilot conflicts. All I can do for now is add a space between the copilot suggestion and our prompt, which I think is okay for now.

## Auto-Suggestions During Typing
I made one other settings change which I think is a pretty major improvement to the typing experience - I've turned off auto-suggestions during typing.

I think this is ideal in most cases, but there's a few where it's not (adding a Value in a sentence, adding some markdown feature mid-text block).

Here's the comparison:

### Before
CleanShot 2023-06-23 at 14 14 46

### After
CleanShot 2023-06-23 at 14 15 25

**Pull request merged**
